In [1]:
import pandas as pd
import sqlite3

In [2]:
#Creating Database Connection 
conn = sqlite3.connect('inventory.db')

In [42]:
tables = pd.read_sql_query("select name from sqlite_master where type= 'table'", conn)
tables

                   name
0       begin_inventory
1         end_inventory
2             purchases
3       purchase_prices
4                 sales
5        vendor_invoice
6  vendor_sales_summary

In [40]:
for table in tables['name']:
    print('-'*50, f'{table}', '-'*50)
    display(pd.read_sql(f"select * from {table}", conn).sample(3))

-------------------------------------------------- begin_inventory --------------------------------------------------

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
20952,9_BLACKPOOL_6724,9,BLACKPOOL,6724,Black Opal Cashmore Cab Svgn,750mL,13,7.99,2024-01-01
133099,55_DRY GULCH_15322,55,DRY GULCH,15322,Vinum Cellars Scrapper Cab F,750mL,10,27.99,2024-01-01
110399,47_PELLA'S WISH_1623,47,PELLA'S WISH,1623,Bulleit 95 Rye,375mL,4,12.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
71972,31_HORNSEY_8123,31,HORNSEY,8123,Mouton Cadet Red Brdx,750mL,12,12.99,2024-12-31
68252,30_CULCHETH_2554,30,CULCHETH,2554,WhistlePig Old World 12 Yr,750mL,3,109.99,2024-12-31
181598,68_SOLARIS_40055,68,SOLARIS,40055,Campo Viejo Gran RSV Rioja,750mL,16,16.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
1137032,33_HORNSEY_3427,33,3427,Stolichnaya Blueberi,1.75L,8664,"STOLI GROUP,(USA) LLC",10964,2024-06-28,2024-07-07,2024-07-13,2024-08-13,17.85,3,53.55,1
1950890,69_MOUNTMEND_3584,69,3584,Absolut Raspberri,750mL,17035,PERNOD RICARD USA,12819,2024-10-28,2024-11-02,2024-11-13,2024-12-13,12.49,10,124.90,1
2114369,49_GARIGILL_3102,49,3102,Smirnoff Traveler,1.75L,3960,DIAGEO NORTH AMERICA INC,13226,2024-11-25,2024-11-29,2024-12-05,2025-01-10,12.94,63,815.22,1

-------------------------------------------------- purchase_prices --------------------------------------------------

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
2068,14974,Mantane Primitivo Puglio,12.99,750mL,750,2,8.90,4425,MARTIGNETTI COMPANIES
10562,38112,Canyon Oaks Znfdl Cal,5.99,750mL,750,2,4.13,10754,PERFECTA WINES
8636,23655,Tavernello Pnt Grigio,4.99,750mL,750,2,3.35,7153,PINE STATE TRADING CO

-------------------------------------------------- vendor_invoice --------------------------------------------------

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
1002,1128,BROWN-FORMAN CORP,2024-03-17,9181,2024-03-03,2024-04-18,14855,170276.77,902.47,None
2284,8673,STE MICHELLE WINE ESTATES,2024-06-13,10340,2024-05-22,2024-07-10,8198,60841.50,279.87,None
1682,8920,TAKARA SAKE USA INC,2024-05-02,9796,2024-04-14,2024-06-11,221,1047.28,5.13,None

-------------------------------------------------- sales --------------------------------------------------

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
16120,9_BLACKPOOL_39716,9,39716,Ravenswood Vntrs Blnd Shiraz,750mL,2,17.98,8.99,2024-12-22,750.0,2,0.22,1392,CONSTELLATION BRANDS INC
12997,9_BLACKPOOL_3452,9,3452,Vanya Light Vodka,1.75L,1,6.99,6.99,2024-12-07,1750.0,1,1.84,9552,M S WALKER INC
19316,9_BLACKPOOL_5096,9,5096,DeKuyper Peachtree Schnapps,750mL,2,21.98,10.99,2024-12-10,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY

In [90]:
purchases = pd.read_sql("select * from purchases ", conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372469,49_GARIGILL_22298,49,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-28,2025-01-09,2025-02-06,8.06,12,96.72,2
2372470,1_HARDERSFIELD_19556,1,19556,Zorvino Bacca Z Blackberry,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-27,2025-01-09,2025-02-06,9.39,12,112.68,2
2372471,66_EANVERNESS_22297,66,22297,Zorvino Vyds Pearz,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-26,2025-01-09,2025-02-06,6.75,12,81.00,2
2372472,69_MOUNTMEND_19557,69,19557,Zorvino Fragole Z Strawberry,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-26,2025-01-09,2025-02-06,9.39,12,112.68,2
2372473,55_DRY GULCH_22298,55,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-28,2025-01-09,2025-02-06,8.06,12,96.72,2

In [68]:
purchase_prices = pd.read_sql("select * from purchase_prices where VendorNumber=4466 ", conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [69]:
vendor_invoice  = pd.read_sql("select * from vendor_invoice  where VendorNumber=4466 ", conn)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [146]:
sale  = pd.read_sql("""select * from sales""", conn)
sale

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,1,10.99,10.99,2024-12-20,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,1,10.99,10.99,2024-12-21,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
2,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,4,43.96,10.99,2024-12-23,750.0,1,3.15,12546,JIM BEAM BRANDS COMPANY
3,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,2,21.98,10.99,2024-12-26,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
4,8_ALNERWICK_5096,8,5096,DeKuyper Peachtree Schnapps,750mL,1,10.99,10.99,2024-12-27,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25358,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-17,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
25359,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-21,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
25360,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,3,77.97,25.99,2024-12-23,750.0,1,2.36,9165,ULTRA BEVERAGE COMPANY LLP
25361,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-24,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
25362,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,2,51.98,25.99,2024-12-29,750.0,1,1.57,9165,ULTRA BEVERAGE COMPANY LLP

In [103]:
purchases.groupby(['Brand'])[['Brand','Quantity', 'Dollars']].sum()

          Brand  Quantity   Dollars
Brand
58        34568      3550  32944.00
60         5820      1633  12084.20
61         1586       312   3307.20
62        35154      3200  91744.00
63        33012      2855  86963.30
...         ...       ...       ...
90089    810801        32   2493.44
90090    180180         6   2689.62
90604   1177852       118   9253.56
90609    996699       321   5457.00
90631  11872661      1938  24690.12

[10664 rows x 3 columns]

In [91]:
sales.groupby(['Brand'])[['SalesQuantity', 'SalesDollars']].sum()

       SalesQuantity  SalesDollars
Brand
3140               2         25.98
5215              25        324.75
5255              13        168.87

•The purchases table contains actual purchase data, including the date of purchase, products (brands) purchased by vendors, the amount paid (in dollars), and the quantity purchased.

•The purchase price column is derived from the purchase_prices table, which provides product-wise actual and purchase prices. The combination of vendor

and brand is unique in this table.

•The vendor_invoice table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO number.

•The sales table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.

As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:

⚫purchase transactions made by vendors

⚫sales transaction data

⚫freight costs for each vendor

⚫ actual product prices from vendors

In [105]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [112]:
Freight_summary = pd.read_sql_query("""Select 
    VendorNumber,
    VendorName,
    sum(Freight) as TotalFreightCost
    from vendor_invoice
    GROUP BY VendorNumber
    ORDER BY VendorNumber""", conn)
freight_summary

     VendorNumber                               VendorName  TotalFreightCost
0               2  IRA GOLDMAN AND WILLIAMS, LLP                       27.08
1              54              AAPER ALCOHOL & CHEMICAL CO              0.48
2              60              ADAMBA IMPORTS INTL INC                367.52
3             105              ALTAMAR BRANDS LLC                      62.39
4             200              AMERICAN SPIRITS EXCHANGE                6.19
..            ...                                      ...               ...
121         98450              Serralles Usa LLC                      856.02
122         99166              STARK BREWING COMPANY                  130.09
123        172662                 SWEETWATER FARM                     178.34
124        173357              TAMWORTH DISTILLING                    202.50
125        201359              FLAVOR ESSENCE INC                       0.09

[126 rows x 3 columns]

In [113]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='object')

In [117]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='object')

In [8]:
Purchase_prices_summary = pd.read_sql_query("""SELECT 
    p.Brand as BrandNo,
    p.VendorNumber,
    p.VendorName,
    pp.Price AS ActualPrice,
    p.PurchasePrice AS PurchasePrice,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) as TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
    ON p.Brand = pp.Brand
    WHERE p.PurchasePrice>0
    GROUP BY p.VendorNumber,p.VendorName,p.Brand
    ORDER BY TotalPurchaseDollars""", conn)
purchase_prices_summary

,BrandNo,VendorNumber,VendorName,ActualPrice,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,3065,7245,PROXIMO SPIRITS INC.,0.99,0.71,1,0.71
1,6127,3960,DIAGEO NORTH AMERICA INC,1.99,1.47,1,1.47
2,9123,3924,HEAVEN HILL DISTILLERIES,0.99,0.74,2,1.48
3,5683,8004,SAZERAC CO INC,0.49,0.39,6,2.34
4,8527,9815,WINE GROUP INC,4.99,1.32,2,2.64
...,...,...,...,...,...,...,...
10687,3545,3960,DIAGEO NORTH AMERICA INC,29.99,21.89,138109,3023206.01
10688,4261,3960,DIAGEO NORTH AMERICA INC,22.99,16.17,201682,3261197.94
10689,8068,17035,PERNOD RICARD USA,24.99,18.24,187407,3418303.68
10690,3405,4425,MARTIGNETTI COMPANIES,28.99,23.19,164038,3804041.22
10691,1233,1128,BROWN-FORMAN CORP,36.99,26.27,145080,3811251.60

In [131]:
sale.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [169]:
sales_summary = pd.read_sql_query("""SELECT 
    VendorNo,
    Brand,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(ExciseTax) AS TotalExciseTax
    FROM Sales
    GROUP BY VendorNo,Brand
    ORDER BY TotalSalesDollars""",conn)
sales_summary

,VendorNo,Brand,TotalSalesPrice,TotalSalesQuantity,TotalSalesDollars,TotalExciseTax
0,8004,5287,0.98,2,0.98,0.10
1,9206,2773,0.99,1,0.99,0.05
2,3252,3933,0.99,2,1.98,0.10
3,3924,9123,0.99,2,1.98,0.10
4,10050,3623,1.98,2,1.98,0.10
...,...,...,...,...,...,...
11267,3960,3545,545778.28,135838,4223107.62,249587.83
11268,3960,4261,420050.01,200412,4475972.88,368242.80
11269,17035,8068,461140.15,187140,4538120.60,343854.07
11270,4425,3405,561512.37,160247,4819073.49,294438.66
11271,1128,1233,672819.31,142049,5101919.51,260999.20

In [149]:
sale.shape[0]

25363

In [167]:
pd.read_sql_query("""Select count(*) from sales""",conn)

   count(*)
0  12825363

In [4]:
# When creating a final table from actual tables it takes "More than half an hour" for query processing.
#So that's why we use CTE(Common Table Expression) for every query, creating a virtual(temporary) table for better performance and it takes 'Less than 2min"
import time
start = time.time()
vendor_sales_summary = pd.read_sql_query(""" WITH FreightSummary AS (
    Select 
        VendorNumber,
        VendorName,
        sum(Freight) as TotalFreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        pp.Price AS ActualPrice,
        p.PurchasePrice AS PurchasePrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) as TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice>0
    GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume
    
),

SalesSummary AS (
    SELECT 
        VendorNo,
        Brand,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(ExciseTax) AS TotalExciseTax
    FROM Sales
    GROUP BY VendorNo,Brand
    
)


SELECT
    ps. VendorNumber,
    ps. VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.TotalFreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps. VendorNumber = ss. VendorNo
    AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC""", conn)

end = time.time()
print(f"Time taken: {(end - start)/60}")

Time taken: 0.905581533908844

In [5]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalFreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07

This query generates a vendor-wise sales and purchase summary, which is valuable for:

Performance Optimization:

    •The query involves heavy joins and aggregations on large datasets like sales and purchases.

    •Storing the pre-aggregated results avoids repeated expensive computations.

    •Helps in analyzing sales, purchases, and pricing for different vendors and brands.

    •Future Benefits of Storing this data for faster Dashboarding & Reporting.

    •Instead of running expensive queries each time, dashboards can fetch data quickly from vendor_sales_summary.

In [12]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                   float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
TotalFreightCost         float64
dtype: object

In [13]:
vendor_sales_summary.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesDollars        0
TotalSalesPrice          0
TotalExciseTax           0
TotalFreightCost         0
dtype: int64

In [14]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP', 'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA',
       'DIAGEO NORTH AMERICA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'MAJESTIC FINE WINES',
       'ULTRA BEVERAGE COMPANY LLP', 'STOLI GROUP,(USA) LLC',
       'PROXIMO SPIRITS INC.', 'MOET HENNESSY USA INC', 'CAMPARI AMERICA',
       'SAZERAC CO INC', 'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'SAZERAC NORTH AMERICA INC.', 'PALM BAY INTERNATIONAL INC',
       'REMY COINTREAU USA INC', 'SIDNEY FRANK IMPORTING CO',
       'E & J GALLO WINERY', 'WILLIAM GRANT & SONS INC',
       'HEAVEN HILL DISTILLERIES', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS', 'CASTLE BRANDS CORP.',
       'SOUTHERN WINE & SPIRITS NE', 'STE MICHELLE WINE ESTATES',
       'TRINCHERO FAMILY ESTATES', 'MHW LTD', 'WINE GROUP INC',
       'PERFECTA WINES', 'LUXCO INC', 'TREASURY WINE ESTATES',
       'DIAGEO CHATEAU ESTATE WINES', 'SHAW ROSS INT L IMP LTD',
       'PINE STATE TRADING CO', 'PHILLIPS PRODUCTS CO.',
       'CALEDONIA SPIRITS INC', 'STATE WINE & SPIRITS',
       'KOBRAND CORPORATION', 'BANFI PRODUCTS CORP',
       'VINEYARD BRANDS INC', 'DELICATO VINEYARDS INC',
       'FABRIZIA SPIRITS LLC', 'DUGGANS DISTILLED PRODUCTS',
       'Serralles Usa LLC', 'SEA HAGG DISTILLERY LLC',
       'OLE SMOKY DISTILLERY LLC', 'VRANKEN AMERICA', 'KLIN SPIRITS LLC',
       'LAIRD & CO', 'ADAMBA IMPORTS INTL INC',
       'LATITUDE BEVERAGE COMPANY', 'FREDERICK WILDMAN & SONS',
       'MCCORMICK DISTILLING CO', 'CHARLES JACQUIN ET CIE INC',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY',
       'AMERICAN VINTAGE BEVERAGE', 'MANGO BOTTLING INC',
       'SWEET BABY VINEYARD', 'NICHE W & S', 'LABELLE VYDS AND WINERY',
       'FLAG HILL WINERY & VINEYARD', 'SMOKY QUARTZ DISTILLERY LLC',
       'PREMIUM PORT WINES, INC.', 'Russian Standard Vodka',
       'Dunn Wine Brokers', 'WEIN BAUER INC', 'BULLY BOY DISTILLERS',
       'ATLANTIC IMPORTING COMPANY', 'PREMIER DISTRIBUTORS',
       'VINILANDIA USA', 'PARK STREET IMPORTS LLC', 'TAKARA SAKE USA INC',
       'SEA BREEZE CELLARS LLC', 'STARK BREWING COMPANY', 'TY KU LLC',
       'PSP WINES', 'TAMWORTH DISTILLING', 'ZORVINO VINEYARDS',
       'SOUTHERN GLAZERS W&S OF NE', 'HOOD RIVER DISTILLERS, Inc.',
       'CRUSH WINES', 'POVERTY LANE ORCHARDS', 'DJINN SPIRITS LLC',
       'MOONLIGHT MEADERY', 'TALL SHIP DISTILLERY LLC',
       'FORTUNE WINE BROKERS LLC', 'BLACK COVE BEVERAGES', 'VINEXTRA INC',
       'SURVILLE ENTERPRISES CORP', 'JEWELL TOWNE VINEYARDS',
       'SWEETWATER FARM', 'ALTAMAR BRANDS LLC', 'CANDIA VINEYARDS',
       'INCREDIBREW INC', 'ALISA CARR BEVERAGES',
       'STELLAR IMPORTING CO LLC', 'FULCHINO VINEYARD INC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'Circa Wines',
       'VINEDREA WINES LLC', 'BLACK PRINCE DISTILLERY INC',
       'VINEYARD BRANDS LLC', 'THE IMPORTED GRAPE LLC',
       'WALPOLE MTN VIEW WINERY', 'GILMANTON WINERY & VINEYARD',
       'HAUNTING WHISPER VYDS', 'STAR INDUSTRIES INC.',
       'LOYAL DOG WINERY', 'R.P.IMPORTS INC', 'THE PIERPONT GROUP LLC',
       'APPOLO VINEYARDS LLC', 'BLACK ROCK SPIRITS LLC',
       'CENTEUR IMPORTS LLC', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE', 'UNCORKED', 'BRONCO WINE COMPANY',
       'MILTONS DISTRIBUTING CO', 'TRUETT HURST', 'LAUREATE IMPORTS CO',
       'FANTASY FINE WINES CORP', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS', 'CAPSTONE INTERNATIONAL',
       'FLAVOR ESSENCE INC'], dtype=object)

In [9]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')

In [10]:
vendor_sales_summary.fillna(0, inplace=True)

In [11]:
#For removing irrelevent space in name
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [15]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

In [16]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars']) * 100

In [17]:
# Mostly value of stockTurnover will be 1 and 0.someting
# 1 : It means vendor purchase 10 stock and sales all 10 stocks
# 0.89 : It means vendor purchase 10 stock but sales less than 10 stocks
# 1.1 : It means vendor purchase 10 stock and sales more than 10 stocks(Maybe vendor have previous stocks)

vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']

In [18]:
vendor_sales_summary['SalesPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [19]:
vendor_sales_summary.head()

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalFreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

In [20]:
#Creating Final dataframe table in database
cursor = conn.cursor()

In [21]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'ActualPrice', 'Volume', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesQuantity', 'TotalSalesDollars',
       'TotalSalesPrice', 'TotalExciseTax', 'TotalFreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalesPurchaseRatio'],
      dtype='object')

In [22]:
cursor.execute("""Create table vendor_sales_summary (
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand INT,
    Description VARCHAR(100),
    PurchasePrice DECIMAL (10,2),
    ActualPrice DECIMAL (10,2),
    Volume INT,
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL (15,2),
    TotalSalesQuantity INT,
    TotalSalesDollars DECIMAL (15,2),
    TotalSalesPrice DECIMAL (15,2),
    TotalExciseTax DECIMAL (15,2),
    TotalFreightCost DECIMAL (15,2),
    GrossProfit DECIMAL (15,2), 
    ProfitMargin DECIMAL (15,2),
    StockTurnover DECIMAL (15,2),
    SalesPurchaseRatio DECIMAL (15,2),
    PRIMARY KEY (VendorNumber, Brand)
);""")

OperationalError: table vendor_sales_summary already exists

In [40]:
vendor_sales_summary = pd.read_sql_query("Select * from vendor_sales_summary limit 5", conn)

In [23]:
vendor_sales_summary.to_sql('vendor_sales_summary', conn, if_exists='replace', index = False)

10692

In [24]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalFreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41,13.31,83.448276,2.500000,6.041667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62,63.32,96.436186,22.333333,28.059829
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87,0.50,25.252525,1.000000,1.337838
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07,141.81,98.974037,72.000000,97.469388
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78,84.43,99.166079,86.000000,119.915493

In [29]:
import os
vendor_sales_summary.to_csv('data/vendor_sales_summary.csv',index = False)